### ISSUE TITLE
Error on calendar sync: Multiple lines read as text: [1, 4]

### ISSUE THREAD

**Issue by rhtenhove** [39aldo39/DecSyncCC#38]
Just installed this and added years of calendar entries using [Calendar Import-Export](https://f-droid.org/en/packages/org.sufficientlysecure.ical/). All seemed to be going well (contacts synced without problems), but it looks like it's stuck on some calendar entry. The error that pops up as a notification after having it sync is `Multiple lines read as text: [1, 4]`.
I can't find (`grep`) `[1, 4]` or parts of that in my imported `.ics` or the synced DecSync dir.

The entry count is:
Android entries: 2695
Processed entries: 2246
DecSync entries: 1357

I am only using it on Android, and use Syncthing to synchronize.

How will I be able to find the culprit? I don't mind deleting a broken entry.

Thanks!

**Comment by 39aldo39** [comment]
That is a very strange error. It means that it expected a file to contain just 1 line, but it contained more than that. I have never seen it before, at it is well defined what files contain just text and what files contain multiple lines...

Anyway, the `[1, 4]` means that the first line is `1` and the second one is `4`. Maybe you do have a file with that pattern (it may be a hidden file)?

**Comment by rhtenhove** [comment]
I've taken a look and indeed found a file, `.decsync-sequence`. It is in the `calendars/colID<id>/new-entries/<device-id>/` directory. It only contains
```
1
4
```
What should I do with it?

**Comment by 39aldo39** [comment]
You could just put `4` in the file, but I think you will lose some events that way. It's best to start over with the import.

**Comment by rhtenhove** [comment]
I went for changing it to 4, and it continued syncing.

Everything seems fine, but I'm not sure. These are now the entries numbers:

Android entries: 2695
Processed entries: 3568
DecSync entries: 2679

No errors have popped up anymore. Any way to check if everything is 'fine'?

None of the numbers seem to exactly add up. For example, new-entries/resources has 2696 files, stored-entries/resources has 2680 files.

**Comment by 39aldo39** [comment]
I don't think all your events are written to the DecSync directory. When it crashes, the app thinks that the event is already written, so it doesn't try again next time. That are probably 16 events from 16 crashes in your case.

It did change the order of writing in a new commit, so that part should be better in the future. Although I hope it isn't needed.

**Comment by rhtenhove** [comment]
Alright, I:
1. Exported the events again with the previously mentioned export tool
2. Deleted the collection in DecSyncCC
3. Created a new collection with a different name (not sure if that could have any influence)
4. Imported the in step 1 exported file

After a bit of processing, all 3 counts now show the same number.

Can you recommend any .ics comparison tools? I can compare both the originally crashing .ics and the one I just created to perhaps find out the culprit so you can prevent a crash for the next person.

**Comment by 39aldo39** [comment]
I don't think the .ics is the problem, but writing a lot of files at the same time. All operations should be sequential, but maybe it got confused for some reason.

**Comment by rhtenhove** [comment]
Alright, the issue is resolved then. Thanks so much!

**Comment by renyuneyun** [comment]
I'm encountering the same error message starting from a few days ago. I have been using radicale-decsync (and DecSyncCC) for a while (with Syncthing) and nothing went wrong previously.
No import was done recently, so something else must have issues. (And even if it's due to imports, I did it on the PC with thunderbird, not on Android.)

I looked at everything under  `calendars/colID<id>/new-entries/<device-id>/`, but nothing contains spectacular information as far as I can tell.
Each directory contains one `.decsync-sequence`, and each contains a single line with each a different number.


Are there anything else I can provide?

By the way, I'm having multiple calendars (combined task lists).

**Comment by AeliusSaionji** [comment]
I got hit with this yesterday.
I do not sync my events anywhere (I just keep backups), so this happened spontaneously in android, with no other potential confounding factors. Something must have gone wrong in decsync itself.

![Screenshot_20211112-184007](https://user-images.githubusercontent.com/4342746/141595786-0240b362-5af8-4748-ae34-4f97d645fbee.png)

**Comment by 39aldo39** [comment]
I am still not sure how it can happen. In your case it looks like a file like `calendars/colID<id>/v2/<app-id>/sequences` is at fault.

**Comment by mehdisadeghi** [comment]
Since a few days ago this error appeared on my android device. I have decsync cc on android and radicale on my pc, glued together with syncthing. I have not changed or imported anything recently, everything was working for over a year. In my case the sequence file looks like this (apparently from radicale):


> {}
> 1":1,"72":1,"0b":1,"df":1,"ef":1,"56":1,"1d":5,"73":1,"a8":1,"42":1,"8d":1,"3e":1,"bc":1,"05":2,"33":1,"f6":1,"17":1,"4d":1,"a1":1,"03":1,"ec":1,"e4":1,"cd":1,"ff":3,"70":1,"4c":1,"2a":1,"af":1,"54":1,"7d":1,"1f":1,"cb":1,"2d":1,"7e":2,"3c":1,"b8":1,"75":1,"91":1,"1c":1,"1b":1,"6a":1,"90":1,"98":1,"27":1,"f2":1,"52":1,"9f":4,"a5":1,"48":1,"e9":1,"8a":1,"58":1,"2c":1,"67":3,"b6":2,"d7":1,"d2":1,"4a":1,"2f":1,"a2":1,"c5":1,"76":1,"2b":1,"86":4,"6e":1,"be":1,"b3":1,"13":1,"ed":1,"8c":1,"04":1,"6f":1,"d6":1,"c4":1,"36":1,"8e":1,"19":1,"info":124,"79":1,"fd":1,"7a":1,"46":1,"ee":1,"ce":1,"e3":1,"b9":1,"16":2}
> 

Any idea how I can debug this? I would <strike>prefer</strike> provide more information if necessary.

**Comment by mehdisadeghi** [comment]
I guess I found a simple workaround at least for my problem. In the android DecSync CC app, I just unchecked my caleandar, pressed refresh button and then again put the checkmark back on my calendar. Problem didn't appear again.

I also noticed that before unchecking the calendar, the entries count (accessible through tripple dot menu of the corresponding calendar) showed some android entries and some decsync entries. After uncheck/check, it shows zero android entries and previous count for decsync entries.

**Comment by justpeanuts** [comment]
why was this issue closed? this is still a problem that keeps happening.

> I also noticed that before unchecking the calendar, the entries count (accessible through tripple dot menu of the corresponding calendar) showed some android entries and some decsync entries. After uncheck/check, it shows zero android entries and previous count for decsync entries.

unfortunately this doesn't work in my case 
I am not sure if the problem is with DecsyncCC or the decsync's evolution plugin... 
Any how this "multiple lines read as text" error occurs to me once every month or every other month etc... and everytime how i solve is to export my calendar data as ics file from simple calendar android app and then delete all calendars in decsync and in all my calendar apps then reimport the backedup ics file and then start setting up decsync fresh.. i have done this more than 3 times now and it is becoming frustrating and decsync has kinda become frustrating to use because of this.

**Comment by AeliusSaionji** [comment]
I haven't been effected again.

Is your decsync folder stored on SD?

**Comment by justpeanuts** [comment]
No, my decsync folder is located in the internal storage of my phone.
 I use syncthing to sync it to my Linux PC and there I use evolution plugin for decsync. My decsync calendar in evolution is also refusing to sync - it does not show any calendar events at all in evolution. The problem with decsync in evolution starts occuring at the same time as when decsync starts showing the "multiple lines read as text" error in android.  


30 Oct 2022, 21:19 by ***@***.***:
